name: publish
on:
    release:
        types:
            - published
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Generate Antlr lexer
              run: npx antlr4ts -o "../src/_generated" "AntlrGlslLexer.g4"
              working-directory: ./syntaxes
            - name: Generate Antlr parser
              run: npx antlr4ts -o "../src/_generated" -no-listener -visitor "AntlrGlslParser.g4"
              working-directory: ./syntaxes
            - name: Build in production mode
              run: npm run build-production
            - name: Package universal
              run: npm run package-universal
            - name: Package to web
              run: npm run package-web
            - name: Package to Windows x64
              run: npm run package-windows-x64
            - name: Package to Mac x64
              run: npm run package-mac-x64
            - name: Package to linux-x64
              run: npm run package-linux-x64
            - name: Publish
              run: npx vsce publish --packagePath $(find . -type f -name "*.vsix" | paste -sd " ")
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
